/* Falas de cliente no jeito que chegam de verdade: abreviação, sem
   acento, com erro de digitação, em caixa alta, com emoji. O tipo ao
   lado é o que o motor DEVERIA reconhecer. Serve para medir o
   reconhecimento antes e depois, em vez de acreditar que melhorou. */
module.exports=[
 ['Oi, quanto fica uma minivan de 10 a 20 de dezembro?','preco'],
 ['qnt fica pra 5 pessoas?','preco'],
 ['Quanto custa???','preco'],
 ['qual o valor','preco'],
 ['me passa o orçamento pfv','preco'],
 ['quanto ta saindo','preco'],
 ['Boa tarde! Queria saber o preco','preco'],
 ['Nossa, achei caro','caro'],
 ['ta caro demais','caro'],
 ['eh muito caro isso','caro'],
 ['puxado o valor hein','caro'],
 ['acima do que eu esperava','caro'],
 ['tem desconto?','desconto'],
 ['da pra fazer um descontinho?','desconto'],
 ['consegue melhorar o valor?','desconto'],
 ['faz por menos?','desconto'],
 ['vou pensar e te falo','pensar'],
 ['deixa eu ver com meu marido','falar_com'],
 ['vou falar com minha esposa','falar_com'],
 ['vi mais barato em outro lugar','concorrente'],
 ['a outra locadora fez por 800','concorrente'],
 ['vcs sao confiaveis?','medo'],
 ['como eu sei que nao eh golpe?','medo'],
 ['nunca ouvi falar de vcs','medo'],
 ['ainda nao comprei a passagem','sem_passagem'],
 ['quero fechar','fechar'],
 ['vamos fechar entao','fechar'],
 ['como faco o pagamento?','pagamento'],
 ['aceita cartao?','pagamento'],
 ['parcela em quantas vezes?','pagamento'],
 ['e se meu voo atrasar?','voo'],
 ['tem cadeirinha pra bebe?','cadeirinha'],
 ['vcs tem cadeirinnha?','cadeirinha'],
 ['o seguro cobre o que?','seguro'],
 ['tem franquia?','seguro'],
 ['o pedagio ta incluso?','pedagio'],
 ['como funciona o sunpass?','pedagio'],
 ['sim','sim'],
 ['isso','sim'],
 ['Bom dia!','saudacao'],
 ['oi tudo bem?','saudacao'],
 ['qual modelo do carro?','modelo'],
 ['eh automatico?','modelo'],
 ['quantas malas cabem?','malas'],
 ['cabe 4 malas grandes?','malas'],
 ['onde devolvo?','devolucao'],
 ['onde retiro o carro?','retirada'],
 ['qual o cambio de hoje?','cambio'],
 ['precisa devolver com tanque cheio?','combustivel'],
 ['tem limite de km?','km'],
 ['preciso de carteira internacional?','documentos'],
 ['posso cancelar depois?','cancelamento'],
 ['posso ir pra georgia?','fora_florida'],
 ['👍','sim'],
 ['ok','sim'],
 ['vou ver e te retorno','pensar'],
 ['me manda os valores','preco'],
 ['e quanto fica no total?','preco'],
 ['mto caro pra mim','caro']
];
